"""
Generates .github/workflows/agentic-stlc.yml for a target repo.

All Agentic STLC pipeline files live in .agentic/ inside the target repo
so the project's own source tree is never touched.

Three-job workflow (mirrors lambdapro/agentic-stlc-kane-hyperexecute):
  Job 1: analyze     — KaneAI verifies acceptance criteria in .agentic/requirements/search.txt
  Job 2: orchestrate — Scenario sync, test gen, HyperExecute, traceability, verdict
  Job 3: summary     — Print GREEN / YELLOW / RED verdict to GitHub step summary

Inline steps are used (no composite actions required) so the workflow is
fully self-contained and readable.
"""
from __future__ import annotations

import textwrap
from pathlib import Path

from repo_analyzer import RepoProfile


def _app_startup_steps(repo_profile: RepoProfile) -> str:
    """
    Generate GHA steps (at 6-space indent, matching the final YAML output)
    that start the target application locally before Kane runs.
    These are inserted via string replacement AFTER textwrap.dedent, so
    no f-string indentation complications.
    """
    wd = repo_profile.app_working_dir or "."
    port = repo_profile.app_port or 3000
    install_cmd = repo_profile.install_cmd or "npm ci"
    start_cmd = repo_profile.start_cmd or "npm start"
    i = "      "   # 6 spaces — matches step-list indent after textwrap.dedent

    return (
        f"{i}- name: Setup Node.js for app\n"
        f"{i}  uses: actions/setup-node@v4\n"
        f"{i}  with:\n"
        f"{i}    node-version: ${{{{ env.NODE_VERSION }}}}\n"
        f"{i}    cache: 'npm'\n"
        f"{i}    cache-dependency-path: {wd}/package-lock.json\n"
        f"\n"
        f"{i}- name: Install app dependencies\n"
        f"{i}  working-directory: {wd}\n"
        f"{i}  run: {install_cmd}\n"
        f"\n"
        f"{i}- name: Install Playwright browsers (Kane local mode)\n"
        f"{i}  run: npx playwright install chromium --with-deps\n"
        f"\n"
        f"{i}- name: Start application (background)\n"
        f"{i}  working-directory: {wd}\n"
        f"{i}  run: |\n"
        f"{i}    {start_cmd} &\n"
        f"{i}    npx wait-on http://localhost:{port} --timeout 60000\n"
        f"{i}  env:\n"
        f"{i}    CI: false\n"
        f"{i}    BROWSER: none\n"
        f"\n"
    )


def _build_workflow(
    repo_profile: RepoProfile,
    kane_project_id: str = "",
    kane_folder_id: str = "",
) -> str:
    target_url = repo_profile.target_url or repo_profile.app_url_local or ""

    local_mode = repo_profile.kane_mode == "local"

    workflow = textwrap.dedent(f"""\
        # Auto-generated by Agentic STLC repo-upgrade skill
        # DO NOT edit manually — re-run the skill to regenerate
        #
        # All pipeline files live in .agentic/ — the project source tree is untouched.
        # Reference pipeline: lambdapro/agentic-stlc-kane-hyperexecute
        name: Agentic STLC — Feature Validation

        on:
          push:
            branches:
              - 'feature/agentic-*'
            paths:
              - '.agentic/requirements/**'
              - '.agentic/scenarios/**'
              - '.agentic/ci/**'
          workflow_dispatch:
            inputs:
              full_run:
                description: 'Run all active scenarios (not just new/updated)'
                required: false
                default: 'true'
                type: boolean
              demo_mode:
                description: 'Use pre-generated Kane results, skip live Kane calls'
                required: false
                default: 'false'
                type: boolean
              target_url:
                description: 'App URL under test (leave empty to use configured default)'
                required: false
                default: '{target_url}'
                type: string

        env:
          NODE_VERSION: "22"
          PYTHON_VERSION: "3.11"
          AGENTIC_DIR: ".agentic"

        jobs:

          # ── Stage 1: KaneAI Functional Verification ─────────────────────────
          analyze:
            name: "Stage 1 · KaneAI Verification"
            runs-on: ubuntu-latest
            outputs:
              requirements-count: ${{{{ steps.validate.outputs.requirements_count }}}}
            steps:
              - uses: actions/checkout@v4

              - name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                  node-version: ${{{{ env.NODE_VERSION }}}}

              - name: Setup Python
                uses: actions/setup-python@v5
                with:
                  python-version: ${{{{ env.PYTHON_VERSION }}}}

              - name: Cache pip
                uses: actions/cache@v4
                with:
                  path: ~/.cache/pip
                  key: pip-${{{{ runner.os }}}}-${{{{ hashFiles('.agentic/requirements.txt') }}}}
                  restore-keys: pip-${{{{ runner.os }}}}-

              - name: Cache Kane results (by requirements hash)
                id: kane-cache
                uses: actions/cache@v4
                with:
                  path: .agentic/requirements/analyzed_requirements.json
                  key: kane-results-${{{{ hashFiles('.agentic/requirements/*.txt') }}}}

              - name: Install Python dependencies
                working-directory: ${{{{ env.AGENTIC_DIR }}}}
                run: |
                  pip install -r requirements.txt --cache-dir ~/.cache/pip -q
                  pip install "protobuf>=6.31.0" -q

              - name: Install Kane CLI
                if: steps.kane-cache.outputs.cache-hit != 'true' && inputs.demo_mode != 'true'
                run: |
                  npm cache clean --force
                  npm install -g @testmuai/kane-cli

              - name: Configure Kane CLI
                if: steps.kane-cache.outputs.cache-hit != 'true' && inputs.demo_mode != 'true'
                run: |
                  kane-cli login --username ${{{{ secrets.LT_USERNAME }}}} --access-key ${{{{ secrets.LT_ACCESS_KEY }}}}
                  {f'kane-cli config project {kane_project_id}' if kane_project_id else '# no project_id configured'}
                  {f'kane-cli config folder  {kane_folder_id}' if kane_folder_id else '# no folder_id configured'}
                env:
                  LT_USERNAME:   ${{{{ secrets.LT_USERNAME }}}}
                  LT_ACCESS_KEY: ${{{{ secrets.LT_ACCESS_KEY }}}}

              - name: Run KaneAI (demo mode)
                if: inputs.demo_mode == 'true'
                working-directory: ${{{{ env.AGENTIC_DIR }}}}
                run: python ci/analyze_requirements.py --demo-mode
                env:
                  DEMO_MODE: "true"

              - name: Run KaneAI (live verification)
                if: steps.kane-cache.outputs.cache-hit != 'true' && inputs.demo_mode != 'true'
                working-directory: ${{{{ env.AGENTIC_DIR }}}}
                run: python ci/analyze_requirements.py
                env:
                  LT_USERNAME:           ${{{{ secrets.LT_USERNAME }}}}
                  LT_ACCESS_KEY:         ${{{{ secrets.LT_ACCESS_KEY }}}}
                  TARGET_URL:            ${{{{ inputs.target_url || '{target_url}' }}}}
                  GITHUB_RUN_NUMBER:     ${{{{ github.run_number }}}}
                  KANE_PROJECT_ID:       "{kane_project_id}"
                  KANE_FOLDER_ID:        "{kane_folder_id}"
                  AGENTIC_STLC_CONFIG:   agentic-stlc.config.yaml

              - name: Validate Stage 1 output
                id: validate
                working-directory: ${{{{ env.AGENTIC_DIR }}}}
                run: |
                  python - <<'PYEOF'
                  import json, sys, os
                  from pathlib import Path
                  p = Path('requirements/analyzed_requirements.json')
                  if not p.exists():
                      print("ERROR: analyzed_requirements.json not found", file=sys.stderr)
                      sys.exit(1)
                  data = json.loads(p.read_text(encoding='utf-8'))
                  print(f"Stage 1 valid: {{len(data)}} requirements analyzed")
                  with open(os.environ.get('GITHUB_OUTPUT', '/dev/null'), 'a') as f:
                      f.write(f"requirements_count={{len(data)}}\\n")
                  PYEOF

              - name: Upload analyzed requirements
                uses: actions/upload-artifact@v4
                if: always()
                with:
                  name: analyzed-requirements
                  path: .agentic/requirements/analyzed_requirements.json
                  retention-days: 30

          # ── Stages 2–7: Orchestrator ─────────────────────────────────────────
          orchestrate:
            name: "Stages 2–7 · Orchestrator"
            needs: analyze
            runs-on: ubuntu-latest
            outputs:
              verdict:             ${{{{ steps.verdict.outputs.verdict }}}}
              pass-rate:           ${{{{ steps.verdict.outputs.pass_rate }}}}
              quality-gates-passed: ${{{{ steps.quality-gates.outputs.gates_passed }}}}
            steps:
              - uses: actions/checkout@v4

              - name: Setup Python
                uses: actions/setup-python@v5
                with:
                  python-version: ${{{{ env.PYTHON_VERSION }}}}

              - name: Cache pip
                uses: actions/cache@v4
                with:
                  path: ~/.cache/pip
                  key: pip-${{{{ runner.os }}}}-${{{{ hashFiles('.agentic/requirements.txt') }}}}
                  restore-keys: pip-${{{{ runner.os }}}}-

              - name: Install Python dependencies
                working-directory: ${{{{ env.AGENTIC_DIR }}}}
                run: pip install -r requirements.txt --cache-dir ~/.cache/pip -q

              - name: Ensure reports directory
                run: mkdir -p .agentic/reports

              - name: Download Stage 1 artifact
                uses: actions/download-artifact@v4
                with:
                  name: analyzed-requirements
                  path: .agentic/requirements

              - name: Validate Stage 1 artifact
                working-directory: ${{{{ env.AGENTIC_DIR }}}}
                run: |
                  python - <<'PYEOF'
                  import json, sys
                  from pathlib import Path
                  p = Path('requirements/analyzed_requirements.json')
                  if not p.exists():
                      print("ERROR: analyzed_requirements.json not found", file=sys.stderr)
                      sys.exit(1)
                  data = json.loads(p.read_text(encoding='utf-8'))
                  assert isinstance(data, list) and len(data) > 0, "Artifact is empty"
                  passed = sum(1 for r in data if r.get('kane_status') == 'passed')
                  print(f"Stage 1 artifact valid: {{len(data)}} requirements, {{passed}} passed")
                  PYEOF

              - name: Download HyperExecute CLI
                run: |
                  curl -fsSL -O https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
                  chmod +x hyperexecute
                  mv hyperexecute .agentic/hyperexecute

              - name: Run Agentic STLC Orchestrator (Stages 2-7)
                working-directory: ${{{{ env.AGENTIC_DIR }}}}
                run: python ci/agent.py
                env:
                  LT_USERNAME:         ${{{{ secrets.LT_USERNAME }}}}
                  LT_ACCESS_KEY:       ${{{{ secrets.LT_ACCESS_KEY }}}}
                  TARGET_URL:          ${{{{ inputs.target_url || '{target_url}' }}}}
                  GITHUB_RUN_NUMBER:   ${{{{ github.run_number }}}}
                  FULL_RUN:            ${{{{ inputs.full_run || 'true' }}}}
                  AGENTIC_STLC_CONFIG: "agentic-stlc.config.yaml"
                  RUN_URL:             "${{{{ github.server_url }}}}/${{{{ github.repository }}}}/actions/runs/${{{{ github.run_id }}}}"

              - name: Generate pipeline metrics
                if: always()
                working-directory: ${{{{ env.AGENTIC_DIR }}}}
                run: python ci/pipeline_metrics.py

              - name: Read release verdict
                id: verdict
                if: always()
                working-directory: ${{{{ env.AGENTIC_DIR }}}}
                run: |
                  python - <<'PYEOF'
                  import json, os
                  from pathlib import Path
                  rec = Path('reports/release_recommendation.json')
                  if rec.exists():
                      data = json.loads(rec.read_text())
                      verdict   = data.get('verdict', 'UNKNOWN')
                      pass_rate = data.get('pass_rate', 0)
                  else:
                      verdict, pass_rate = 'UNKNOWN', 0
                  he_job_id = ""
                  api = Path('reports/api_details.json')
                  if api.exists():
                      he_job_id = json.loads(api.read_text()).get('he_job_id', '')
                  with open(os.environ.get('GITHUB_OUTPUT', '/dev/null'), 'a') as f:
                      f.write(f"verdict={{verdict}}\\n")
                      f.write(f"pass_rate={{pass_rate}}\\n")
                      f.write(f"he_job_id={{he_job_id}}\\n")
                  PYEOF

              - name: Read quality gates result
                id: quality-gates
                if: always()
                working-directory: ${{{{ env.AGENTIC_DIR }}}}
                run: |
                  python - <<'PYEOF'
                  import json, os
                  from pathlib import Path
                  qg = Path('reports/quality_gates.json')
                  gates_passed = str(json.loads(qg.read_text()).get('gates_passed', False)).lower() if qg.exists() else 'false'
                  with open(os.environ.get('GITHUB_OUTPUT', '/dev/null'), 'a') as f:
                      f.write(f"gates_passed={{gates_passed}}\\n")
                  PYEOF

              - name: Upload pipeline reports
                uses: actions/upload-artifact@v4
                if: always()
                with:
                  name: pipeline-reports
                  path: |
                    .agentic/reports/
                    .agentic/scenarios/scenarios.json
                    .agentic/tests/playwright/test_powerapps.py
                  retention-days: 30

          # ── Summary ──────────────────────────────────────────────────────────
          summary:
            name: "Pipeline Summary"
            needs: [analyze, orchestrate]
            runs-on: ubuntu-latest
            if: always()
            steps:
              - name: "Print final verdict"
                run: |
                  echo "## Agentic STLC — ${{{{ needs.orchestrate.outputs.verdict }}}}" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
                  echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
                  echo "| Verdict | **${{{{ needs.orchestrate.outputs.verdict }}}}** |" >> $GITHUB_STEP_SUMMARY
                  echo "| Pass rate | ${{{{ needs.orchestrate.outputs.pass-rate }}}}% |" >> $GITHUB_STEP_SUMMARY
                  echo "| Quality gates | ${{{{ needs.orchestrate.outputs.quality-gates-passed }}}} |" >> $GITHUB_STEP_SUMMARY
                  echo "| Requirements analyzed | ${{{{ needs.analyze.outputs.requirements-count }}}} |" >> $GITHUB_STEP_SUMMARY
                  echo "| Run | [${{{{ github.run_id }}}}](https://github.com/${{{{ github.repository }}}}/actions/runs/${{{{ github.run_id }}}}) |" >> $GITHUB_STEP_SUMMARY
    """)

    # Post-process: insert app startup steps before Kane CLI install (local mode only)
    if local_mode:
        startup = _app_startup_steps(repo_profile)
        workflow = workflow.replace(
            "      - name: Install Kane CLI\n",
            startup + "      - name: Install Kane CLI\n",
            1,
        )

    return workflow


def inject(
    repo_profile: RepoProfile,
    workspace_dir: str,
    kane_objective: str = "",
    he_config_name: str = "hyperexecute.yaml",
    kane_project_id: str = "",
    kane_folder_id: str = "",
) -> str:
    """
    Write .github/workflows/agentic-stlc.yml to the workspace.
    Returns the relative path to the written file.
    """
    workspace = Path(workspace_dir)
    workflows_dir = workspace / ".github" / "workflows"
    workflows_dir.mkdir(parents=True, exist_ok=True)

    dest = workflows_dir / "agentic-stlc.yml"
    content = _build_workflow(repo_profile, kane_project_id, kane_folder_id)
    dest.write_text(content, encoding="utf-8")
    rel = str(dest.relative_to(workspace)).replace("\\", "/")
    print(f"[gha_injector] wrote {rel}")
    return rel
