
name: Github-coPilot Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  HyperExecute-Playwright:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone https://github.com/gagan-lambda/contosotraders-cloudtesting.git
          echo "STEP 2) Download CLI and setting environment variables"
              cd src/ContosoTraders.Ui.Website
              npm install
              npm run start &
              echo "Triggering sanity tests on LambdaTest"
              response=$(curl --location 'https://test-manager-api.lambdatest.com/api/atm/v1/hyperexecute' \
              --header 'accept: application/json' \
              --header 'Content-Type: application/json' \
              --header 'Authorization:  Basic bXVkYXNzYXJzOk04QVFyR1F2Z2NwMFI1VE9pTm15allNQ29ETEt6cVpRMTBEMllHb0tPY2thclVyYnFK' \
              --data '{
                "test_run_id" : "01JT11BRJ1EWC42SND2XWCJYWQ",
                "concurrency" : 4,
                "tunnel": "mudassar"
              }')
            echo "Response: $response"
            job_id=$(echo $response | jq -r '.job_id')
            echo "Job ID: $job_id"
            echo "::set-output name=job_id::$job_id"